import type { MetaFunction } from "@remix-run/node";
import { Link } from "@remix-run/react";

import { SUPPORT_EMAIL } from "../lib/links";

export const meta: MetaFunction = () => [
  { title: "Privacy Policy · TryOn" },
  {
    name: "description",
    content:
      "How TryOn handles shopper photos and merchant data: photos are never stored, GDPR webhooks are honored, and shop data is deleted on uninstall.",
  },
];

// Keep this in sync with any material change to data handling.
const LAST_UPDATED = "May 22, 2026";

export default function Privacy() {
  return (
    <div className="tryon-privacy-page">
      <style>{CSS}</style>

      <header className="nav">
        <div className="wrap nav-inner">
          <Link className="brand" to="/">
            TryOn<span className="dot">.</span>
          </Link>
          <Link className="back" to="/">
            ← Back to home
          </Link>
        </div>
      </header>

      <main className="wrap doc">
        <h1>Privacy Policy</h1>
        <p className="updated">Last updated: {LAST_UPDATED}</p>

        <p className="lede">
          TryOn (&ldquo;the app&rdquo;) adds an AI virtual try-on widget to
          Shopify storefronts. This policy explains exactly what data the app
          processes, what it stores, and what it never stores — for shoppers
          who use the try-on widget and for merchants who install the app.
        </p>

        <section>
          <h2>Shopper photos are never stored</h2>
          <p>
            When a shopper uploads a photo to try on a garment, that image is
            sent to our server, passed in-memory to the AI image model (Google
            Gemini via Google Cloud Vertex AI) to generate the try-on result,
            and then discarded. The uploaded photo and the generated result are{" "}
            <strong>never written to any database, disk, or log</strong>. They
            exist only for the few seconds it takes to produce the result and
            are gone the moment the request completes or the shopper closes the
            window.
          </p>
        </section>

        <section>
          <h2>What we do store</h2>
          <p>For each try-on, we record an image-free event row containing:</p>
          <ul>
            <li>the product the try-on was for (title, handle, and URL);</li>
            <li>
              whether the generation succeeded or failed, and how long it took;
            </li>
            <li>a timestamp;</li>
            <li>
              a <strong>salted SHA-256 hash of the visitor&rsquo;s IP address</strong>.
            </li>
          </ul>
          <p>
            The IP hash is one-way and salted with a private key. It cannot be
            reversed to an IP address and is not personally identifiable. It is
            used solely to enforce the per-visitor try-on rate limit the
            merchant configures — nothing else. We never store the raw IP
            address.
          </p>
          <p>
            We also store the merchant&rsquo;s configuration (shop domain,
            widget settings, rate-limit settings, plan), aggregate add-to-cart
            counts, and, for order-conversion analytics, basic order metadata
            received from Shopify&rsquo;s order webhook — the order id, total,
            currency, item count, and whether a purchased product had been tried
            on. We do <strong>not</strong> read or store any customer-identifiable
            order fields (no names, emails, addresses, or phone numbers). None of
            this contains shopper personal data.
          </p>
        </section>

        <section>
          <h2>Data we never collect</h2>
          <ul>
            <li>Shopper names, emails, addresses, or payment details.</li>
            <li>Uploaded or generated photos (see above).</li>
            <li>Raw IP addresses.</li>
            <li>Tracking cookies or cross-site advertising identifiers.</li>
          </ul>
        </section>

        <section>
          <h2>Subprocessors</h2>
          <p>
            Try-on images are generated by <strong>Google Gemini</strong> via
            Google Cloud Vertex AI. Photos are transmitted to Google only for
            the duration of generating a result and are subject to Google
            Cloud&rsquo;s data-processing terms. Application data and analytics
            are stored in a managed PostgreSQL database, isolated to this
            app&rsquo;s own schema. Hosting is provided by Vercel.
          </p>
        </section>

        <section>
          <h2>Merchant data &amp; uninstalling</h2>
          <p>
            When a merchant uninstalls TryOn, the app immediately disables the
            widget and clears its access tokens. In line with Shopify&rsquo;s
            requirements, when Shopify sends the{" "}
            <code>shop/redact</code> request (48 hours after uninstall) the app{" "}
            <strong>permanently hard-deletes all data for that shop</strong> —
            the shop record and every associated try-on event, add-to-cart
            event, and order event — with no recoverable copy.
          </p>
        </section>

        <section>
          <h2>GDPR &amp; mandatory compliance webhooks</h2>
          <p>
            The app implements all of Shopify&rsquo;s mandatory privacy
            webhooks:
          </p>
          <ul>
            <li>
              <strong>customers/data_request</strong> — the app stores no
              customer-identifiable data, so there is nothing to export; the
              request is acknowledged.
            </li>
            <li>
              <strong>customers/redact</strong> — no customer-identifiable data
              is stored (try-on events carry only a non-identifiable IP hash),
              so there is nothing to delete; the request is acknowledged.
            </li>
            <li>
              <strong>shop/redact</strong> — all data for the shop is
              permanently deleted, as described above.
            </li>
          </ul>
          <p>
            All webhooks are HMAC-verified using the app&rsquo;s secret before
            any action is taken.
          </p>
        </section>

        <section>
          <h2>Children</h2>
          <p>
            The widget is intended for use by adults on merchant storefronts. We
            do not knowingly process photos of children.
          </p>
        </section>

        <section>
          <h2>Changes to this policy</h2>
          <p>
            We may update this policy as the app evolves. Material changes will
            be reflected by the &ldquo;Last updated&rdquo; date above.
          </p>
        </section>

        <section>
          <h2>Contact</h2>
          <p>
            Questions about privacy or data handling? Email{" "}
            <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
          </p>
        </section>
      </main>

      <footer className="wrap foot">
        <Link to="/">TryOn</Link>
        <span>© {new Date().getFullYear()} · Virtual try-on for Shopify</span>
      </footer>
    </div>
  );
}

const CSS = `
.tryon-privacy-page {
  --paper: #f7f5f2; --line: #e3ddd3; --ink: #111; --mute: #6b6b6b; --accent: #e8624a;
  background: var(--paper); color: var(--ink);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, sans-serif;
  -webkit-font-smoothing: antialiased; line-height: 1.6; min-height: 100vh;
}
.tryon-privacy-page * { box-sizing: border-box; }
.tryon-privacy-page a { color: inherit; }
.wrap { max-width: 760px; margin: 0 auto; padding: 0 24px; }

.nav { position: sticky; top: 0; z-index: 20; background: rgba(247,245,242,0.85);
  backdrop-filter: saturate(140%) blur(12px); border-bottom: 1px solid var(--line); }
.nav-inner { height: 64px; display: flex; align-items: center; justify-content: space-between; max-width: 760px; margin: 0 auto; padding: 0 24px; }
.brand { font-weight: 700; font-size: 18px; letter-spacing: -0.02em; text-decoration: none; }
.brand .dot { color: var(--accent); }
.back { font-size: 14px; color: var(--mute); text-decoration: none; }
.back:hover { color: var(--ink); }

.doc { padding: 56px 24px 40px; }
.doc h1 { font-size: clamp(32px, 5vw, 44px); letter-spacing: -0.02em; font-weight: 600; margin: 0; }
.updated { color: var(--mute); font-size: 14px; margin: 8px 0 28px; }
.lede { font-size: 18px; color: #333; margin: 0 0 8px; }
.doc section { margin-top: 36px; }
.doc h2 { font-size: 20px; font-weight: 600; letter-spacing: -0.01em; margin: 0 0 10px; }
.doc p { margin: 0 0 12px; color: #2a2a2a; }
.doc ul { margin: 0 0 12px; padding-left: 22px; color: #2a2a2a; }
.doc li { margin-bottom: 6px; }
.doc code { background: #efece7; border: 1px solid var(--line); border-radius: 5px;
  padding: 1px 6px; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.9em; }
.doc a { color: var(--accent); text-decoration: underline; text-underline-offset: 2px; }

.foot { display: flex; align-items: center; justify-content: space-between;
  padding: 28px 24px; color: var(--mute); font-size: 13px; border-top: 1px solid var(--line); margin-top: 48px; }
.foot a { text-decoration: none; }

@media (max-width: 640px) {
  .foot { flex-direction: column; gap: 8px; }
}
`;
